CREATE SCHEMA IF NOT EXISTS SCRAPER AUTHORIZATION SA

========================================================
========================================================
========================================================
CREATE TABLE IF NOT EXISTS AGENCY (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT AGENCY_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS CITY (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT CITY_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS DISTRICT (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT DISTRICT_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS ENERGY_CERTIFICATION (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT ENERGY_CERTIFICATION_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS OPERATION_TYPE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT OPERATION_TYPE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS PUBLICITY (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT PUBLICITY_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS REALTY_TYPE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT REALTY_TYPE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAP_SOURCE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	URL VARCHAR(100) NOT NULL,
	CONSTRAINT SCRAP_SOURCE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SELLER (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	PHONE VARCHAR(100),
	EMAIL VARCHAR(100),
	CONSTRAINT SELLER_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS STATE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT STATE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SUBDISTRICT (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT SUBDISTRICT_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS TAG (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT TAG_PK PRIMARY KEY (ID)
) ;

CREATE TABLE TAG_REFERENCE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TAG_ID BIGINT,
	ADVERTISEMENT_ID BIGINT,
	CONSTRAINT TAG_REFERENCE_PK PRIMARY KEY (ID),
	CONSTRAINT TAG_REFERENCE_ADVERTISEMENT_FK FOREIGN KEY (ADVERTISEMENT_ID) REFERENCES SCRAPER.ADVERTISEMENT(ID),
	CONSTRAINT TAG_REFERENCE_TAG_FK FOREIGN KEY (TAG_ID) REFERENCES SCRAPER.TAG(ID)
) ;

CREATE TABLE SCRAPER.ADVERTISEMENT (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255),
	OPERATION_TYPE_ID INTEGER NOT NULL,
	REALTY_TYPE_ID INTEGER NOT NULL,
	PROVINCE VARCHAR(100),
	LISTING_DATE DATE,
	VIEWS_COUNT VARCHAR(100),
	ADDRESS VARCHAR(255),
	STATE_ID INTEGER NOT NULL,
	CITY_ID INTEGER NOT NULL,
	POSTAL_CODE VARCHAR(100),
	DESCRIPTION VARCHAR(10000),
	BEDROOMS TINYINT,
	BATHROOMS TINYINT,
	M2_SIZE INTEGER,
	PRICE DECIMAL(65535,32767),
	ENERGY_CERTIFICATION_ID INTEGER,
	PUBLICITY_ID INTEGER,
	SELLER_ID BIGINT NOT NULL,
	URL VARCHAR(1000) NOT NULL,
	HAS_IMAGES BOOLEAN,
	TIMESTAMP_SCRAPED TIMESTAMP NOT NULL,
	SCRAP_SOURCE_ID INTEGER NOT NULL,
	CONSTRAINT ADVERTISEMENT_PK PRIMARY KEY (ID),
	CONSTRAINT ADVERTISEMENT_CITY_FK FOREIGN KEY (CITY_ID) REFERENCES SCRAPER.CITY(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_ENERGY_CERTIFICATION_FK FOREIGN KEY (ENERGY_CERTIFICATION_ID) REFERENCES SCRAPER.ENERGY_CERTIFICATION(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_OPERATION_TYPE_FK FOREIGN KEY (OPERATION_TYPE_ID) REFERENCES SCRAPER.OPERATION_TYPE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_PUBLICITY_FK FOREIGN KEY (PUBLICITY_ID) REFERENCES SCRAPER.PUBLICITY(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_REALTY_TYPE_FK FOREIGN KEY (REALTY_TYPE_ID) REFERENCES SCRAPER.REALTY_TYPE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_SCRAP_SOURCE_FK FOREIGN KEY (SCRAP_SOURCE_ID) REFERENCES SCRAPER.SCRAP_SOURCE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_SELLER_FK FOREIGN KEY (SELLER_ID) REFERENCES SCRAPER.SELLER(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_STATE_FK FOREIGN KEY (STATE_ID) REFERENCES SCRAPER.STATE(ID) ON DELETE RESTRICT ON UPDATE CASCADE
) ;
========================================================
========================================================
========================================================
CREATE TABLE IF NOT EXISTS SCRAPER.AGENCY (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT AGENCY_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.CITY (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT CITY_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.DISTRICT (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT DISTRICT_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.ENERGY_CERTIFICATION (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT ENERGY_CERTIFICATION_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.OPERATION_TYPE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT OPERATION_TYPE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.PUBLICITY (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT PUBLICITY_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.REALTY_TYPE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT REALTY_TYPE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.SCRAP_SOURCE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	URL VARCHAR(100) NOT NULL,
	CONSTRAINT SCRAP_SOURCE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.SELLER (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100),
	PHONE VARCHAR(100) ,
	EMAIL VARCHAR(100),
	CONSTRAINT SELLER_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.STATE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT STATE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.SUBDISTRICT (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT SUBDISTRICT_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAPER.TAG (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT TAG_PK PRIMARY KEY (ID)
) ;

CREATE TABLE SCRAPER.ADVERTISEMENT (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255),
	OPERATION_TYPE_ID INTEGER NOT NULL,
	REALTY_TYPE_ID INTEGER NOT NULL,
	PROVINCE VARCHAR(100),
	LISTING_DATE DATE,
	VIEWS_COUNT VARCHAR(100),
	ADDRESS VARCHAR(255),
	STATE_ID INTEGER NOT NULL,
	CITY_ID INTEGER NOT NULL,
	POSTAL_CODE VARCHAR(100),
	DESCRIPTION VARCHAR(10000),
	BEDROOMS TINYINT,
	BATHROOMS TINYINT,
	M2_SIZE INTEGER,
	PRICE DECIMAL(65535,32767),
	ENERGY_CERTIFICATION_ID INTEGER,
	PUBLICITY_ID INTEGER,
	SELLER_ID BIGINT NOT NULL,
	URL VARCHAR(1000) NOT NULL,
	HAS_IMAGES BOOLEAN,
	TIMESTAMP_SCRAPED TIMESTAMP NOT NULL,
	SCRAP_SOURCE_ID INTEGER NOT NULL,
	CONSTRAINT ADVERTISEMENT_PK PRIMARY KEY (ID),
	CONSTRAINT ADVERTISEMENT_CITY_FK FOREIGN KEY (CITY_ID) REFERENCES SCRAPER.CITY(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_ENERGY_CERTIFICATION_FK FOREIGN KEY (ENERGY_CERTIFICATION_ID) REFERENCES SCRAPER.ENERGY_CERTIFICATION(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_OPERATION_TYPE_FK FOREIGN KEY (OPERATION_TYPE_ID) REFERENCES SCRAPER.OPERATION_TYPE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_PUBLICITY_FK FOREIGN KEY (PUBLICITY_ID) REFERENCES SCRAPER.PUBLICITY(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_REALTY_TYPE_FK FOREIGN KEY (REALTY_TYPE_ID) REFERENCES SCRAPER.REALTY_TYPE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_SCRAP_SOURCE_FK FOREIGN KEY (SCRAP_SOURCE_ID) REFERENCES SCRAPER.SCRAP_SOURCE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_SELLER_FK FOREIGN KEY (SELLER_ID) REFERENCES SCRAPER.SELLER(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_STATE_FK FOREIGN KEY (STATE_ID) REFERENCES SCRAPER.STATE(ID) ON DELETE RESTRICT ON UPDATE CASCADE
) ;

CREATE TABLE SCRAPER.TAG_REFERENCE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TAG_ID BIGINT,
	ADVERTISEMENT_ID BIGINT,
	CONSTRAINT TAG_REFERENCE_PK PRIMARY KEY (ID),
	CONSTRAINT TAG_REFERENCE_ADVERTISEMENT_FK FOREIGN KEY (ADVERTISEMENT_ID) REFERENCES SCRAPER.ADVERTISEMENT(ID),
	CONSTRAINT TAG_REFERENCE_TAG_FK FOREIGN KEY (TAG_ID) REFERENCES SCRAPER.TAG(ID)
) ;
========================================================
========================================================
========================================================




DROP TABLE IF EXISTS AGENCY, ADVERTISEMENT, CITY, DISTRICT, ENERGY_CERTIFICATION, OPERATION_TYPE, PUBLICITY, REALTY_TYPE, SCRAP_SOURCE, SELLER, STATE, SUBDISTRICT, TAG, TAG_REFERENCE

ALTER TABLE ADVERTISEMENT RENAME CONSTRAINT ADVERTISEMENT_PUBLICITY_FK TO PUBLICITY_ID

ALTER TABLE SCRAPER.DISTRICT DROP CONSTRAINT DISTRICT_PK ;
ALTER TABLE SCRAPER.DISTRICT ADD CONSTRAINT DISTRICT_PK PRIMARY KEY (ID) ;

ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT CITY_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT OPERATION_TYPE_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT ENERGY_CERTIFICATION_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT PUBLICITY_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT REALTY_TYPE_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT SCRAP_SOURCE_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT SELLER_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT STATE_ID ;

CREATE INDEX ADVERTISEMENT_CITY_FK_INDEX_8 ON ADVERTISEMENT (CITY_ID) ;
CREATE INDEX ADVERTISEMENT_ENERGY_CERTIFICATION_FK_INDEX_8 ON ADVERTISEMENT (ENERGY_CERTIFICATION_ID) ;
CREATE INDEX ADVERTISEMENT_OPERATION_TYPE_FK_INDEX_8 ON ADVERTISEMENT (OPERATION_TYPE_ID) ;
CREATE INDEX ADVERTISEMENT_PUBLICITY_FK_INDEX_8 ON ADVERTISEMENT (PUBLICITY_ID) ;
CREATE INDEX ADVERTISEMENT_REALTY_TYPE_FK_INDEX_8 ON ADVERTISEMENT (REALTY_TYPE_ID) ;
CREATE INDEX ADVERTISEMENT_SCRAP_SOURCE_FK_INDEX_8 ON ADVERTISEMENT (SCRAP_SOURCE_ID) ;
CREATE INDEX ADVERTISEMENT_SELLER_FK_INDEX_8 ON ADVERTISEMENT (SELLER_ID) ;
CREATE INDEX ADVERTISEMENT_STATE_FK_INDEX_8 ON ADVERTISEMENT (STATE_ID) ;
CREATE UNIQUE INDEX PRIMARY_KEY_8 ON ADVERTISEMENT (ID) ;

ALTER TABLE SCRAPER.SELLER ADD PHONE VARCHAR(100) ;
ALTER TABLE SCRAPER.SELLER ADD EMAIL VARCHAR(100) ;