CREATE TABLE IF NOT EXISTS AGENCY (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT AGENCY_PK PRIMARY KEY (ID)
) ;


CREATE TABLE IF NOT EXISTS DISTRICT (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT DISTRICT_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SCRAP_SOURCE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	URL VARCHAR(100) NOT NULL,
	CONSTRAINT SCRAP_SOURCE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SUBDISTRICT (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT SUBDISTRICT_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS OPERATION_TYPE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT OPERATION_TYPE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS REALTY_TYPE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT REALTY_TYPE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS ENERGY_CERTIFICATION (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT ENERGY_CERTIFICATION_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS PUBLICITY (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT PUBLICITY_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS SELLER (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	CONSTRAINT SELLER_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS TAG (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT TAG_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS STATE (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT STATE_PK PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS CITY (
	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	CONSTRAINT CITY_PK PRIMARY KEY (ID)
) ;

CREATE TABLE ADVERTISEMENT (
	ID BIGINT DEFAULT (NEXT VALUE FOR SCRAPER.SYSTEM_SEQUENCE_CA9C1140_57F0_43C9_A92A_4B26EBFC71CB) NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255),
	PROVINCE VARCHAR(100),
	LISTING_DATE DATE,
	VIEWS_COUNT INTEGER,
	ADDRESS VARCHAR(100),
	POSTAL_CODE VARCHAR(100),
	DESCRIPTION VARCHAR(10000),
	BEDROOMS TINYINT,
	BATHROOMS TINYINT,
	M2_SIZE INTEGER,
	PRICE DECIMAL(65535,32767),
	HAS_IMAGES BOOLEAN,
	TIMESTAMP_SCRAPED TIMESTAMP,
	CONSTRAINT ADVERTISEMENT_PK PRIMARY KEY (ID),
	CONSTRAINT CITY_ID FOREIGN KEY (ID) REFERENCES CITY(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ENERGY_CERTIFICATION_ID FOREIGN KEY (ID) REFERENCES ENERGY_CERTIFICATION(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT OPERATION_TYPE_ID FOREIGN KEY (ID) REFERENCES OPERATION_TYPE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT PUBLICITY_ID FOREIGN KEY (ID) REFERENCES PUBLICITY(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT REALTY_TYPE_ID FOREIGN KEY (ID) REFERENCES REALTY_TYPE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT SCRAP_SOURCE_ID FOREIGN KEY (ID) REFERENCES SCRAP_SOURCE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT SELLER_ID FOREIGN KEY (ID) REFERENCES SELLER(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT STATE_ID FOREIGN KEY (ID) REFERENCES STATE(ID) ON DELETE RESTRICT ON UPDATE CASCADE
) ;
CREATE UNIQUE INDEX PRIMARY_KEY_B ON ADVERTISEMENT (ID) ;

ALTER TABLE ADVERTISEMENT RENAME CONSTRAINT ADVERTISEMENT_PUBLICITY_FK TO PUBLICITY_ID

ALTER TABLE SCRAPER.DISTRICT DROP CONSTRAINT DISTRICT_PK ;
ALTER TABLE SCRAPER.DISTRICT ADD CONSTRAINT DISTRICT_PK PRIMARY KEY (ID) ;

ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT CITY_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT OPERATION_TYPE_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT ENERGY_CERTIFICATION_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT PUBLICITY_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT REALTY_TYPE_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT SCRAP_SOURCE_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT SELLER_ID ;
ALTER TABLE SCRAPER.ADVERTISEMENT DROP CONSTRAINT STATE_ID ;

CREATE TABLE ADVERTISEMENT (
	ID BIGINT DEFAULT (NEXT VALUE FOR SCRAPER.SYSTEM_SEQUENCE_1FC97683_54A8_43A7_A63E_23131CA838EA) NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255),
	OPERATION_TYPE_ID INTEGER NOT NULL,
	REALTY_TYPE_ID INTEGER NOT NULL,
	PROVINCE VARCHAR(100),
	LISTING_DATE DATE,
	VIEWS_COUNT INTEGER,
	ADDRESS VARCHAR(255),
	STATE_ID INTEGER NOT NULL,
	CITY_ID INTEGER NOT NULL,
	POSTAL_CODE VARCHAR(100),
	DESCRIPTION VARCHAR(10000),
	BEDROOMS TINYINT,
	BATHROOMS TINYINT,
	M2_SIZE INTEGER,
	PRICE DECIMAL(65535,32767),
	ENERGY_CERTIFICATION_ID INTEGER,
	PUBLICITY_ID INTEGER,
	SELLER_ID BIGINT NOT NULL,
	URL VARCHAR(1000) NOT NULL,
	HAS_IMAGES BOOLEAN,
	TIMESTAMP_SCRAPED TIMESTAMP NOT NULL,
	SCRAP_SOURCE_ID INTEGER NOT NULL,
	CONSTRAINT ADVERTISEMENT_PK PRIMARY KEY (ID),
	CONSTRAINT ADVERTISEMENT_CITY_FK FOREIGN KEY (CITY_ID) REFERENCES CITY(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_ENERGY_CERTIFICATION_FK FOREIGN KEY (ENERGY_CERTIFICATION_ID) REFERENCES ENERGY_CERTIFICATION(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_OPERATION_TYPE_FK FOREIGN KEY (OPERATION_TYPE_ID) REFERENCES OPERATION_TYPE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_PUBLICITY_FK FOREIGN KEY (PUBLICITY_ID) REFERENCES PUBLICITY(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_REALTY_TYPE_FK FOREIGN KEY (REALTY_TYPE_ID) REFERENCES REALTY_TYPE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_SCRAP_SOURCE_FK FOREIGN KEY (SCRAP_SOURCE_ID) REFERENCES SCRAP_SOURCE(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_SELLER_FK FOREIGN KEY (SELLER_ID) REFERENCES SELLER(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT ADVERTISEMENT_STATE_FK FOREIGN KEY (STATE_ID) REFERENCES STATE(ID) ON DELETE RESTRICT ON UPDATE CASCADE
) ;
CREATE INDEX ADVERTISEMENT_CITY_FK_INDEX_8 ON ADVERTISEMENT (CITY_ID) ;
CREATE INDEX ADVERTISEMENT_ENERGY_CERTIFICATION_FK_INDEX_8 ON ADVERTISEMENT (ENERGY_CERTIFICATION_ID) ;
CREATE INDEX ADVERTISEMENT_OPERATION_TYPE_FK_INDEX_8 ON ADVERTISEMENT (OPERATION_TYPE_ID) ;
CREATE INDEX ADVERTISEMENT_PUBLICITY_FK_INDEX_8 ON ADVERTISEMENT (PUBLICITY_ID) ;
CREATE INDEX ADVERTISEMENT_REALTY_TYPE_FK_INDEX_8 ON ADVERTISEMENT (REALTY_TYPE_ID) ;
CREATE INDEX ADVERTISEMENT_SCRAP_SOURCE_FK_INDEX_8 ON ADVERTISEMENT (SCRAP_SOURCE_ID) ;
CREATE INDEX ADVERTISEMENT_SELLER_FK_INDEX_8 ON ADVERTISEMENT (SELLER_ID) ;
CREATE INDEX ADVERTISEMENT_STATE_FK_INDEX_8 ON ADVERTISEMENT (STATE_ID) ;
CREATE UNIQUE INDEX PRIMARY_KEY_8 ON ADVERTISEMENT (ID) ;



