INSERT INTO AGENCY
(NAME)
VALUES
('Moja stoliza'),
('Tvoi dom'),
('Kvadratnyi metr');

INSERT INTO CITY
(NAME)
VALUES
('Madrid'),
('Barcelona'),
('Sevilla');

INSERT INTO DISTRICT
(NAME)
VALUES
('District #1'),
('District #2'),
('Main district')

INSERT INTO ENERGY_CERTIFICATION
(NAME)
VALUES
('Non certificado'),
('Best energy')

INSERT INTO OPERATION_TYPE
(NAME)
VALUES
('Byu'),
('Sell'),
('Rent');

INSERT INTO PUBLICITY
(NAME)
VALUES
('Private'),
('Public');

INSERT INTO REALTY_TYPE
(NAME)
VALUES
('Flat'),
('House'),
('Room'),
('Office'),
('Garage');

INSERT INTO SCRAP_SOURCE
(NAME, URL)
VALUES
('idealista', 'http://www.idealista.com'),
('pisos', 'http://www.pisos.com');

INSERT INTO SELLER
(NAME, LAST_NAME)
VALUES
('Ivan', 'Pronin'),
('Nicholas', 'Salguero'),
('John', 'Connor');

INSERT INTO STATE
(NAME)
VALUES
('Catalonia'),
('Madridista'),
('Valencia state');

INSERT INTO SUBDISTRICT
(NAME)
VALUES
('Subdistrict #1'),
('Subdistrict #2'),
('Main subdistrict');

INSERT INTO TAG
(NAME)
VALUES
('TV set'),
('Wi-fi'),
('Parking');

INSERT INTO ADVERTISEMENT
(TITLE, OPERATION_TYPE_ID, REALTY_TYPE_ID, PROVINCE, LISTING_DATE, VIEWS_COUNT, ADDRESS, STATE_ID, CITY_ID, POSTAL_CODE, DESCRIPTION, BEDROOMS, BATHROOMS, M2_SIZE, PRICE, ENERGY_CERTIFICATION_ID, PUBLICITY_ID, SELLER_ID, URL, HAS_IMAGES, TIMESTAMP_SCRAPED, SCRAP_SOURCE_ID)
VALUES('title', 2, 2, 'province', CURRENT_DATE(), 22, 'address', 2, 2, 'postal_code', 'description', 3, 3, 44, 55.5, 2, 2, 2, 'http://idelaista.com/ad=54', false, CURRENT_TIMESTAMP(), 1);

INSERT INTO SCRAPER.ADVERTISEMENT (ID,TITLE,OPERATION_TYPE_ID,REALTY_TYPE_ID,PROVINCE,LISTING_DATE,VIEWS_COUNT,ADDRESS,STATE_ID,CITY_ID,POSTAL_CODE,DESCRIPTION,BEDROOMS,BATHROOMS,M2_SIZE,PRICE,ENERGY_CERTIFICATION_ID,PUBLICITY_ID,SELLER_ID,URL,HAS_IMAGES,TIMESTAMP_SCRAPED,SCRAP_SOURCE_ID) VALUES (
1,'title',2,2,'province','2017-12-03',22,'address',2,2,'postal_code','description',3,3,44,55.5,2,2,2,'http://idelaista.com/ad=54',false,'2017-12-03 18:07:34.284',1);
INSERT INTO SCRAPER.ADVERTISEMENT (ID,TITLE,OPERATION_TYPE_ID,REALTY_TYPE_ID,PROVINCE,LISTING_DATE,VIEWS_COUNT,ADDRESS,STATE_ID,CITY_ID,POSTAL_CODE,DESCRIPTION,BEDROOMS,BATHROOMS,M2_SIZE,PRICE,ENERGY_CERTIFICATION_ID,PUBLICITY_ID,SELLER_ID,URL,HAS_IMAGES,TIMESTAMP_SCRAPED,SCRAP_SOURCE_ID) VALUES (
4,'title2',2,2,'province2','2017-12-03',22,'address2',2,2,'postal_code2','description2',1,2,57,180,2,2,2,'http://idelaista.com/ad=180',false,'2017-12-03 18:10:58.000',1);
INSERT INTO SCRAPER.ADVERTISEMENT (ID,TITLE,OPERATION_TYPE_ID,REALTY_TYPE_ID,PROVINCE,LISTING_DATE,VIEWS_COUNT,ADDRESS,STATE_ID,CITY_ID,POSTAL_CODE,DESCRIPTION,BEDROOMS,BATHROOMS,M2_SIZE,PRICE,ENERGY_CERTIFICATION_ID,PUBLICITY_ID,SELLER_ID,URL,HAS_IMAGES,TIMESTAMP_SCRAPED,SCRAP_SOURCE_ID) VALUES (
5,'3rd title',1,2,'3rd province','2017-12-03',5,'This is 3rd address',2,2,'postal_code n3','3rd desc is ok!!',2,4,63,2000,2,2,2,'http://idelaista.com/ad=2000',true,'2017-12-03 18:14:17.173',1);



